// <auto-generated />
using System;
using BookSpace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSpace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookSpaceDbContext))]
    [Migration("20260826085842_AddGlobalUserEmailUniqueness")]
    partial class AddGlobalUserEmailUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSpace.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalRequests");

                    b.HasAlternateKey("BookingId")
                        .HasName("UQ_ApprovalRequests_Booking");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_ApprovalRequests_Pending")
                        .HasFilter("[Decision] = 'Pending'");

                    b.ToTable("ApprovalRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalRequests_Decision", "[Decision] IN ('Pending','Approved','Rejected','Expired')");

                            t.HasCheckConstraint("CK_ApprovalRequests_DecisionPaired", "([Decision] = 'Pending' AND [DecidedByUserId] IS NULL AND [DecidedAtUtc] IS NULL) OR ([Decision] <> 'Pending' AND [DecidedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.AvailabilityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("OpensAt")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Weekday")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_AvailabilityWindows");

                    b.HasIndex("ResourceId");

                    b.ToTable("AvailabilityWindows", null, t =>
                        {
                            t.HasCheckConstraint("CK_AvailabilityWindows_Weekday", "[Weekday] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_AvailabilityWindows_Window", "[ClosesAt] > [OpensAt]");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.BlackoutPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_BlackoutPeriods");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ResourceId", "StartsAtUtc")
                        .HasDatabaseName("IX_BlackoutPeriods_Resource_Start");

                    b.ToTable("BlackoutPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_BlackoutPeriods_Interval", "[EndsAtUtc] > [StartsAtUtc]");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckedInAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Bookings");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RecurrenceRuleId")
                        .HasDatabaseName("IX_Bookings_Series")
                        .HasFilter("[RecurrenceRuleId] IS NOT NULL");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("IX_Bookings_NoShowSweep")
                        .HasFilter("[Status] = 'Confirmed' AND [CheckedInAtUtc] IS NULL");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "ResourceId");

                    b.HasIndex("ResourceId", "StartsAtUtc")
                        .HasDatabaseName("IX_Bookings_Resource_Start");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ResourceId", "StartsAtUtc"), new[] { "EndsAtUtc", "Status", "Quantity" });

                    b.HasIndex("OrgId", "UserId", "StartsAtUtc")
                        .HasDatabaseName("IX_Bookings_User");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Interval", "[EndsAtUtc] > [StartsAtUtc]");

                            t.HasCheckConstraint("CK_Bookings_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Bookings_Status", "[Status] IN ('Pending','Confirmed','Rejected','Cancelled','Completed','NoShow')");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK_Notifications");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("SendAtUtc")
                        .HasDatabaseName("IX_Notifications_Due")
                        .HasFilter("[SentAtUtc] IS NULL");

                    b.HasIndex("BookingId", "RecurrenceRuleId", "OccurrenceDate", "RecipientUserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UQ_Notifications_Once");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_HasContext", "[BookingId] IS NOT NULL OR ([RecurrenceRuleId] IS NOT NULL AND [OccurrenceDate] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Notifications_Kind", "[Kind] IN ('Confirmed','Rejected','Cancelled','Reminder','ApprovalRequested','NoShowReleased','RecurrenceOccurrenceSkipped')");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApprovalExpiryHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NoShowGraceMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ReminderLeadMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Organizations");

                    b.HasAlternateKey("Slug")
                        .HasName("UQ_Organizations_Slug");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Organizations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Organizations_Status", "[Status] IN ('Active','Suspended')");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LocalEndTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int?>("OccurrenceCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RecurrenceRules");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("RecurrenceRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurrenceRules_EndCondition", "([EndDate] IS NOT NULL AND [OccurrenceCount] IS NULL) OR ([EndDate] IS NULL AND [OccurrenceCount] IS NOT NULL)");

                            t.HasCheckConstraint("CK_RecurrenceRules_Frequency", "[Frequency] IN ('Daily','Weekly','Monthly')");

                            t.HasCheckConstraint("CK_RecurrenceRules_Interval", "[IntervalValue] > 0");

                            t.HasCheckConstraint("CK_RecurrenceRules_MaxSpan", "[EndDate] IS NULL OR [EndDate] <= DATEADD(YEAR, 2, [StartDate])");

                            t.HasCheckConstraint("CK_RecurrenceRules_Status", "[Status] IN ('Active','Cancelled')");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasAlternateKey("TokenHash")
                        .HasName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshTokens_Family");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Resources");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("UQ_Resources_Org_Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Capacity", "[Capacity] > 0");
                        });
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarFeedToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasAlternateKey("CalendarFeedToken")
                        .HasName("UQ_Users_CalendarFeedToken");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("OrgId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.Booking", null)
                        .WithOne()
                        .HasForeignKey("BookSpace.Domain.Entities.ApprovalRequest", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalRequests_Bookings");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ApprovalRequests_Users");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.AvailabilityWindow", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.Resource", null)
                        .WithMany("AvailabilityWindows")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityWindows_Resources");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.BlackoutPeriod", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BlackoutPeriods_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlackoutPeriods_Resources");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_BlackoutPeriods_UpdatedBy");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Bookings_CancelledBy");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.RecurrenceRule", null)
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Bookings_RecurrenceRules");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Bookings_UpdatedBy");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Users");

                    b.HasOne("BookSpace.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("OrgId", "ResourceId")
                        .HasPrincipalKey("OrgId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Resources_SameOrg");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notifications_Bookings");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Notifications_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.HasOne("BookSpace.Domain.Entities.RecurrenceRule", null)
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Notifications_RecurrenceRules");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Organization", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Organizations_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Organizations_UpdatedBy");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.RecurrenceRule", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RecurrenceRules_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RecurrenceRules_Resources");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RecurrenceRules_UpdatedBy");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RecurrenceRules_Users");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RefreshTokens_Replacement");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Resource", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Resources_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Resources_Organizations");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Resources_UpdatedBy");

                    b.OwnsMany("BookSpace.Domain.Entities.Resource+ApproverAssignment", "_approverAssignments", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ResourceId", "UserId")
                                .HasName("PK_ResourceApprovers");

                            b1.HasIndex("UserId");

                            b1.ToTable("ResourceApprovers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("FK_ResourceApprovers_Resources");

                            b1.HasOne("BookSpace.Domain.Entities.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("FK_ResourceApprovers_Users");
                        });

                    b.Navigation("_approverAssignments");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.User", b =>
                {
                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Users_CreatedBy");

                    b.HasOne("BookSpace.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Users_Organizations");

                    b.HasOne("BookSpace.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Users_UpdatedBy");

                    b.OwnsMany("BookSpace.Domain.Entities.User+RoleAssignment", "_roleAssignments", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Role")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("UserId", "Role")
                                .HasName("PK_UserRoles");

                            b1.ToTable("UserRoles", null, t =>
                                {
                                    t.HasCheckConstraint("CK_UserRoles_Role", "[Role] IN ('SysAdmin','TenantAdmin','Approver','Member')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("FK_UserRoles_Users");
                        });

                    b.Navigation("_roleAssignments");
                });

            modelBuilder.Entity("BookSpace.Domain.Entities.Resource", b =>
                {
                    b.Navigation("AvailabilityWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
